DROP DATABASE IF EXISTS `escendol`;
CREATE DATABASE IF NOT EXISTS `escendol`;
USE `escendol`;

DROP TABLE IF EXISTS `VLR`;
CREATE TABLE IF NOT EXISTS `VLR`(
`TANGGAL` date,
`NEW_SALES_AREA` varchar(20),
`NEW_CLUSTER` varchar(20),
`LACSACXD` varchar(20),
`LAC` int,
`CELL_ID` int,
`KECAMATAN` varchar(20),
`NAMA_CSM` varchar(50),
`MICRO_CLUSTER` varchar(20),
`VLR` int
);

DROP TABLE IF EXISTS `TRX_OUTLET`;
CREATE TABLE IF NOT EXISTS `TRX_OUTLET`(
`TANGGAL` date,
`SALES_AREA` varchar(20),
`NAMA_CLUSTER` varchar(20),
`ORGANIZATION_ID` int,
`ORGANIZATION_NAME` varchar(20),
`AMOUNT_DEBIT` int
);

DROP TABLE IF EXISTS `TRAFIK`;
CREATE TABLE IF NOT EXISTS `TRAFIK`(
`TANGGAL` date,
`SITEID` varchar(8),
`LAC` varchar(20),
`CELL_ID` int,
`SITE_NAME` varchar(25),
`CELL_NAME` varchar(25),
`NEW_SALES_AREA` varchar(20),
`NEW_CLUSTER` varchar(20),
`MICRO_CLUSTER` varchar(20),
`KECAMATAN` varchar(20),
`VOICE` float,
`TRAFIK` float
);

DROP TABLE IF EXISTS `REVENUE`;
CREATE TABLE IF NOT EXISTS `REVENUE`(
`BULAN` date,
`SITEID` varchar(8),
`LAC` varchar(20),
`CELL_ID` int,
`SITE_NAME` varchar(25),
`CELL_NAME` varchar(25),
`NEW_SALES_AREA` varchar(20),
`NEW_CLUSTER` varchar(20),
`MICRO_CLUSTER` varchar(20),
`KECAMATAN` varchar(20),
`REVENUE` float
);

DROP TABLE IF EXISTS `UTILISASI_SA_SURABAYA`;
CREATE TABLE IF NOT EXISTS `UTILISASI_SA_SURABAYA`(
`SITENAME` varchar(25),
`CELLNAME` varchar(25),
`SITEID` varchar(8),
`REGION` varchar(10),
`CELLID` int,
`BAND` varchar(20),
`CELL_TYPE` varchar(20),
`LONG` float,
`LAT` float,
`VENDOR` varchar(20),
`PGB` varchar(20),
`MICRO_CLUSTER` varchar(20),
`CLUSTER` varchar(20),
`SALES_AREA` varchar(20),
`HSDPA_USER_W27` float,
`HSDPA_USER_W28` float,
`HSDPA_USER_W29` float,
`HSDPA_USER_W30` float,
`HSDPA_USER_W31` float,
`HSDPA_USER_W32` float,
`HSDPA_USER_W33` float,
`HSDPA_USER_W34` float,
`HSDPA_USER_W35` float,
`HSDPA_USER_W36` float,
`KATEGORY_W33` varchar(20),
`KATEGORY_W34` varchar(20),
`KATEGORY_W35` varchar(20),
`KATEGORY_W36` varchar(20)
);

DROP TABLE IF EXISTS `REVENUE_SURABAYA`;
CREATE TABLE IF NOT EXISTS `REVENUE_SURABAYA`(
`BULAN` date,
`SALES_AREA` varchar(20),
`CLUSTER` varchar(20),
`ACT` int,
`TARGET` int
);

LOAD DATA INFILE 'D:\TRAFIK.txt' INTO TABLE TRAFIK
(@VAR1, SITEID, LAC, CELL_ID, SITE_NAME, CELL_NAME, NEW_SALES_AREA, NEW_CLUSTER, MICRO_CLUSTER, KECAMATAN, VOICE , TRAFIK)
SET TANGGAL = STR_TO_DATE(@VAR1, '%m/%d/%Y');

LOAD DATA INFILE 'D:\VLR.txt' INTO TABLE VLR FIELDS TERMINATED  ';'
(@VAR1, NEW_SALES_AREA, NEW_CLUSTER, LACSACXD, LAC, CELL_ID, KECAMATAN, NAMA_CSM, MICRO_CLUSTER,VLR)
SET TANGGAL = STR_TO_DATE(@VAR1, '%m/%d/%Y');

LOAD DATA INFILE 'D:\TRX_OUTLET.txt' INTO TABLE TRX_OUTLET FIELDS TERMINATED BY ';';

LOAD DATA INFILE 'D:\REVENUE.txt' INTO TABLE REVENUE FIELDS TERMINATED BY ';';

LOAD DATA INFILE 'D:\Utilisasi SA Surabaya.csv' INTO TABLE UTILISASI_SA_SURABAYA FIELDS TERMINATED BY ',';