--SHEET 1 NOMOR 1
DROP TABLE IF EXISTS `GROWTH_VLR`;
CREATE TABLE IF NOT EXISTS `GROWTH_VLR` (
  `TANGGAL` DATE DEFAULT NULL,
  `VLR` INT(11) DEFAULT NULL,
  `VLR_SEBELUMNYA` INT(11) DEFAULT NULL,
  `PERSENTASE` VARCHAR(10) DEFAULT NULL,
  `KETERANGAN` VARCHAR(20) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
DELIMITER $$

CREATE OR REPLACE PROCEDURE DELETE_GROWTH_VLR(IN KEYWORD DATE)
	BEGIN
		DELETE FROM `GROWTH_VLR` WHERE MONTH(`TANGGAL`) = MONTH(KEYWORD) AND YEAR(`TANGGAL`) = YEAR(KEYWORD);
	END$$
CREATE OR REPLACE PROCEDURE GROWTH_VLR(IN KEYWORD DATE) 
	BEGIN 
		DECLARE COUNTER INT;
		DECLARE TANGGAL DATE; 
		DECLARE VLR INT;
		DECLARE VLR_SEBELUMNYA INT;
		DECLARE KETERANGAN VARCHAR(20);
		DECLARE DONE INT DEFAULT 0; 
		DECLARE CUR1 CURSOR FOR SELECT V.TANGGAL, MAX(V.VLR) AS VLR FROM VLR V WHERE MONTH(V.TANGGAL) = MONTH(KEYWORD) AND YEAR(V.TANGGAL) = YEAR(KEYWORD) AND V.MICRO_CLUSTER = 'MC-SURABAYA_1_1' GROUP BY V.TANGGAL; 
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=1; 
		SELECT COUNT(*) INTO COUNTER FROM VLR V WHERE MONTH(V.TANGGAL) = MONTH(KEYWORD) AND YEAR(V.TANGGAL) = YEAR(KEYWORD) AND V.MICRO_CLUSTER = 'MC-SURABAYA_1_1';
		IF COUNTER > 0 THEN
			CALL DELETE_GROWTH_VLR(KEYWORD);
			
			OPEN CUR1;
				LOOPING:LOOP 
					FETCH CUR1 INTO TANGGAL, VLR; 
					IF DONE = 1 THEN 
						LEAVE LOOPING; 
					ELSE
						SELECT MAX(V.VLR) INTO VLR_SEBELUMNYA FROM VLR V WHERE V.TANGGAL = DATE_SUB(TANGGAL, INTERVAL 1 MONTH) AND V.MICRO_CLUSTER = 'MC-SURABAYA_1_1';
						IF (VLR > VLR_SEBELUMNYA OR VLR_SEBELUMNYA IS NULL) THEN
							SET KETERANGAN = 'NAIK';
						ELSE
							SET KETERANGAN = 'TURUN';
						END IF;
						INSERT INTO GROWTH_VLR VALUES(TANGGAL, VLR, VLR_SEBELUMNYA, (CONCAT(ROUND(( ABS(VLR-VLR_SEBELUMNYA)/VLR_SEBELUMNYA * 100 ),2),'%')), KETERANGAN);
					END IF;
				END LOOP LOOPING; 
			CLOSE CUR1; 
			SELECT V.TANGGAL, V.VLR, V.VLR_SEBELUMNYA, V.PERSENTASE, V.KETERANGAN FROM (SELECT MAX(X.VLR) AS MAX FROM GROWTH_VLR X WHERE MONTH(X.TANGGAL) = MONTH(KEYWORD) AND YEAR(X.TANGGAL) = YEAR(KEYWORD)) M, GROWTH_VLR V WHERE MONTH(V.TANGGAL) = MONTH(KEYWORD) AND YEAR(V.TANGGAL) = YEAR(KEYWORD) AND V.VLR = M.MAX;
		END IF;
	END$$
	
--SHEET 2 NOMOR 2
DROP TABLE IF EXISTS `GROWTH_TRAFIK`;
CREATE TABLE IF NOT EXISTS `GROWTH_TRAFIK` (
  `TANGGAL` DATE DEFAULT NULL,
  `TRAFIK` INT(11) DEFAULT NULL,
  `TRAFIK_SEBELUMNYA` INT(11) DEFAULT NULL,
  `PERSENTASE` VARCHAR(10) DEFAULT NULL,
  `KETERANGAN` VARCHAR(20) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
DELIMITER $$

CREATE OR REPLACE PROCEDURE DELETE_GROWTH_TRAFIK(IN KEYWORD DATE)
	BEGIN
		DELETE FROM `GROWTH_TRAFIK` WHERE MONTH(`TANGGAL`) = MONTH(KEYWORD) AND YEAR(`TANGGAL`) = YEAR(KEYWORD);
	END$$
CREATE OR REPLACE PROCEDURE GROWTH_TRAFIK(IN KEYWORD DATE) 
	BEGIN 
		DECLARE COUNTER INT;
		DECLARE TANGGAL DATE; 
		DECLARE TRAFIK INT;
		DECLARE TRAFIK_SEBELUMNYA INT;
		DECLARE KETERANGAN VARCHAR(20);
		DECLARE DONE INT DEFAULT 0; 
		DECLARE CUR1 CURSOR FOR SELECT T.TANGGAL, MAX(T.TRAFIK) AS TRAFIK FROM TRAFIK T WHERE MONTH(T.TANGGAL) = MONTH(KEYWORD) AND YEAR(T.TANGGAL) = YEAR(KEYWORD) AND T.MICRO_CLUSTER = 'MC-SURABAYA_1_1' GROUP BY T.TANGGAL; 
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=1; 
		SELECT COUNT(*) INTO COUNTER FROM TRAFIK T WHERE MONTH(T.TANGGAL) = MONTH(KEYWORD) AND YEAR(T.TANGGAL) = YEAR(KEYWORD) AND T.MICRO_CLUSTER = 'MC-SURABAYA_1_1';
		IF COUNTER > 0 THEN
			CALL DELETE_GROWTH_TRAFIK(KEYWORD);
			
			OPEN CUR1;
				LOOPING:LOOP 
					FETCH CUR1 INTO TANGGAL, TRAFIK; 
					IF DONE = 1 THEN 
						LEAVE LOOPING; 
					ELSE
						SELECT MAX(T.TRAFIK) INTO TRAFIK_SEBELUMNYA FROM TRAFIK T WHERE T.TANGGAL = DATE_SUB(TANGGAL, INTERVAL 1 MONTH) AND T.MICRO_CLUSTER = 'MC-SURABAYA_1_1';
						IF (TRAFIK > TRAFIK_SEBELUMNYA OR TRAFIK_SEBELUMNYA IS NULL) THEN
							SET KETERANGAN = 'NAIK';
						ELSE
							SET KETERANGAN = 'TURUN';
						END IF;
						INSERT INTO GROWTH_TRAFIK VALUES(TANGGAL, TRAFIK, TRAFIK_SEBELUMNYA, (CONCAT(ROUND(( ABS(TRAFIK-TRAFIK_SEBELUMNYA)/TRAFIK_SEBELUMNYA * 100 ),2),'%')), KETERANGAN);
					END IF;
				END LOOP LOOPING; 
			CLOSE CUR1; 
			SELECT T.TANGGAL, T.TRAFIK, T.TRAFIK_SEBELUMNYA, T.PERSENTASE, T.KETERANGAN FROM (SELECT MAX(X.TRAFIK) AS MAX FROM GROWTH_TRAFIK X WHERE MONTH(X.TANGGAL) = MONTH(KEYWORD) AND YEAR(X.TANGGAL) = YEAR(KEYWORD)) M, GROWTH_TRAFIK T WHERE MONTH(T.TANGGAL) = MONTH(KEYWORD) AND YEAR(T.TANGGAL) = YEAR(KEYWORD) AND T.TRAFIK = M.MAX;
		END IF;
	END$$

--SHEET 2 NOMOR 3
DROP TABLE IF EXISTS `GROWTH_REVENUE`;
CREATE TABLE IF NOT EXISTS `GROWTH_REVENUE` (
  `BULAN` DATE DEFAULT NULL,
  `REVENUE` INT(11) DEFAULT NULL,
  `REVENUE_SEBELUMNYA` INT(11) DEFAULT NULL,
  `PERSENTASE` VARCHAR(10) DEFAULT NULL,
  `KETERANGAN` VARCHAR(20) DEFAULT NULL
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;
DELIMITER $$

CREATE OR REPLACE PROCEDURE DELETE_GROWTH_REVENUE(IN KEYWORD DATE)
	BEGIN
		DELETE FROM `GROWTH_REVENUE` WHERE MONTH(`BULAN`) = MONTH(KEYWORD) AND YEAR(`BULAN`) = YEAR(KEYWORD);
	END$$
CREATE OR REPLACE PROCEDURE GROWTH_REVENUE(IN KEYWORD DATE) 
	BEGIN 
		DECLARE COUNTER INT;
		DECLARE BULAN DATE; 
		DECLARE REVENUE INT;
		DECLARE REVENUE_SEBELUMNYA INT;
		DECLARE KETERANGAN VARCHAR(20);
		DECLARE DONE INT DEFAULT 0; 
		DECLARE CUR1 CURSOR FOR SELECT R.BULAN, MAX(R.REVENUE) AS REVENUE FROM REVENUE R WHERE MONTH(R.BULAN) = MONTH(KEYWORD) AND YEAR(R.BULAN) = YEAR(KEYWORD) AND R.MICRO_CLUSTER = 'MC-SURABAYA_1_1' GROUP BY R.BULAN; 
		DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE=1; 
		SELECT COUNT(*) INTO COUNTER FROM REVENUE R WHERE MONTH(R.BULAN) = MONTH(KEYWORD) AND YEAR(R.BULAN) = YEAR(KEYWORD) AND R.MICRO_CLUSTER = 'MC-SURABAYA_1_1';
		IF COUNTER > 0 THEN
			CALL DELETE_GROWTH_REVENUE(KEYWORD);
			
			OPEN CUR1;
				LOOPING:LOOP 
					FETCH CUR1 INTO BULAN, REVENUE; 
					IF DONE = 1 THEN 
						LEAVE LOOPING; 
					ELSE
						SELECT MAX(R.REVENUE) INTO REVENUE_SEBELUMNYA FROM REVENUE R WHERE R.BULAN = DATE_SUB(BULAN, INTERVAL 1 MONTH) AND R.MICRO_CLUSTER = 'MC-SURABAYA_1_1';
						IF (REVENUE > REVENUE_SEBELUMNYA OR REVENUE_SEBELUMNYA IS NULL) THEN
							SET KETERANGAN = 'NAIK';
						ELSE
							SET KETERANGAN = 'TURUN';
						END IF;
						INSERT INTO GROWTH_REVENUE VALUES(BULAN, REVENUE, REVENUE_SEBELUMNYA, (CONCAT(ROUND(( ABS(REVENUE-REVENUE_SEBELUMNYA)/REVENUE_SEBELUMNYA * 100 ),2),'%')), KETERANGAN);
					END IF;
				END LOOP LOOPING; 
			CLOSE CUR1; 
			SELECT R.BULAN, R.REVENUE, R.REVENUE_SEBELUMNYA, R.PERSENTASE, R.KETERANGAN FROM (SELECT MAX(X.REVENUE) AS MAX FROM GROWTH_REVENUE X WHERE MONTH(X.BULAN) = MONTH(KEYWORD) AND YEAR(X.BULAN) = YEAR(KEYWORD)) M, GROWTH_REVENUE R WHERE MONTH(R.BULAN) = MONTH(KEYWORD) AND YEAR(R.BULAN) = YEAR(KEYWORD) AND R.REVENUE = M.MAX;
		END IF;
	END$$

--SHEET 1 NOMOR 5
SELECT ORGANIZATION_NAME
FROM `TRX_OUTLET` 
ORDER BY AMOUNT_DEBIT DESC
LIMIT 1;

--SHEET 1 NOMOR 5.1
SELECT AMOUNT_DEBIT
FROM `TRX_OUTLET`
WHERE MONTH(TANGGAL)=CURRENT_DATE() AND YEAR(TANGGAL)=YEAR(CURRENT_DATE()
GROUP BY TANGGAL;

--SHEET 1 NOMOR 5.2
SELECT AVG(AMOUNT_DEBIT)
FROM `TRX_OUTLET`
WHERE YEAR(TANGGAL)=YEAR(CURRENT_DATE())
GROUP BY MONTH(TANGGAL)

--SHEET 1 NOMOR 7--
SELECT SITEID
FROM `UTILISASI_SA_SURABAYA` 
WHERE MICRO_CLUSTER='MC-SURABAYA_1_1'
GROUP BY CELLID
ORDER BY HSDPA_USER_W36 ASC
LIMIT 5;

--SHEET 1 NOMOR 8
SELECT ORGANIZATION_NAME
FROM `TRX_OUTLET` 
WHERE MONTH(TANGGAL)=MONTH(CURRENT_DATE())
GROUP BY ORGANIZATION_ID 
ORDER BY AVG(AMOUNT_DEBIT) ASC 
LIMIT 5;

--SHEET 2 NOMOR 1
--DAILY
SELECT VLR
FROM `VLR`
WHERE MICRO_CLUSTER='MC-SURABAYA_1_1' AND MONTH(TANGGAL)=MONTH(CURRENT_DATE()) AND YEAR(TANGGAL)=YEAR(CURRENT_DATE()
ORDER BY TANGGAL;

--MONTHLY
SELECT VLR
FROM `VLR`
WHERE MICRO_CLUSTER='MC-SURABAYA_1_1' AND YEAR(TANGGAL)=YEAR(CURRENT_DATE())
ORDER BY MONTH(TANGGAL)=MONTH(CURRENT_DATE());

--SHEET 2 NOMOR 1.1
SELECT NAMA_CSM, TANGGAL 
FROM `VLR` 
WHERE MICRO_CLUSTER='MC-SURABAYA_1_1' AND DAYNAME(TANGGAL)='WEDNESDAY'
GROUP BY TANGGAL;

--SHEET 2 NOMOR 1.2 ERROR
SELECT NAMA_CSM, TANGGAL 
	FROM `VLR` 
	WHERE MICRO_CLUSTER='MC-SURABAYA_1_1' 
	AND DAYNAME(TANGGAL)='WEDNESDAY' 
	AND DATE(TANGGAL)>='YEAR(TANGGAL)=YEAR(CURRENT_DATE())-(MONTH(TANGGAL)=MONTH(CURRENT_DATE())-1)-23' 
	AND DATE(TANGGAL)<='YEAR(TANGGAL)=YEAR(CURRENT_DATE())-MONTH(TANGGAL)=MONTH(CURRENT_DATE())-(1-7)'
	GROUP BY TANGGAL;

--SHEET 2 NOMOR 2
--DAILY
SELECT TRAFIK
FROM `TRAFIK`
WHERE MICRO_CLUSTER='MC-SURABAYA_1_1' AND MONTH(TANGGAL)=MONTH(CURRENT_DATE()) AND YEAR(TANGGAL)=YEAR(CURRENT_DATE()
ORDER BY TANGGAL;

--MONTHLY
SELECT TRAFIK
FROM `TRAFIK`
WHERE MICRO_CLUSTER='MC-SURABAYA_1_1' AND YEAR(TANGGAL)=YEAR(CURRENT_DATE())
ORDER BY MONTH(TANGGAL)=MONTH(CURRENT_DATE());

--SHEET 2 NOMOR 3
SELECT ACT/TARGET*100 AS PERCENTAGE, TARGET
FROM `REVENUE_SURABAYA`
WHERE BULAN='SEPTEMBER';
